# Generated by Django 5.0.2 on 2024-03-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regulatory_document_of_manufacture', models.CharField(max_length=100)),
                ('receipt_date', models.DateField()),
                ('instance', models.FloatField()),
                ('qualification', models.CharField(max_length=50)),
                ('shipment', models.CharField(max_length=10)),
                ('date_of_manufacture', models.DateField()),
                ('best_before_date', models.DateField()),
                ('date_of_consumption', models.DateField(blank=True, null=True)),
                ('quantity_of_consumption', models.FloatField(blank=True, null=True)),
                ('remainder', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
